#!/bin/sh

# Переходим в рабочую дирректрию с миграциями или в каталог где находится инструмент миграции

if [ "${STAGE}" = "production" ]; then
    cd /database/migrations
    export OVERLOAD_API_DB_ADDR=host:port
    export OVERLOAD_API_DB_NAME=dbname
    export OVERLOAD_API_DB_USER=dbuser
    export OVERLOAD_API_DB_PASS=dbpass
elif [ "${STAGE}" = "staging" ]; then
    cd /database/migrations
    export OVERLOAD_API_DB_ADDR=host:port
    export OVERLOAD_API_DB_NAME=dbname
    export OVERLOAD_API_DB_USER=dbuser
    export OVERLOAD_API_DB_PASS=dbpass
elif [ "${STAGE}" = "development" ]; then
    cd migrations
    export OVERLOAD_API_DB_ADDR=host:port
    export OVERLOAD_API_DB_NAME=dbname
    export OVERLOAD_API_DB_USER=dbuser
    export OVERLOAD_API_DB_PASS=dbpass
fi
nc -vz $OVERLOAD_API_DB_ADDR 5432
echo $OVERLOAD_API_DB_ADDR |xxd -a
if [ "$1" = "--dryrun" ]; then
    goose -dir . postgres "host=${OVERLOAD_API_DB_ADDR} user=${OVERLOAD_API_DB_USER} dbname=${OVERLOAD_API_DB_NAME} password=${OVERLOAD_API_DB_PASS} sslmode=disable" status
else
    goose -dir . postgres "host=${OVERLOAD_API_DB_ADDR} user=${OVERLOAD_API_DB_USER} dbname=${OVERLOAD_API_DB_NAME} password=${OVERLOAD_API_DB_PASS} sslmode=disable" up
fi
