// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: overload.proto

package overload

import (
	"context"

	desc "github.com/x-yield/over-api/pkg/overload-service"
)

func (i *Implementation) GetJob(ctx context.Context, req *desc.JobRequest) (*desc.JobResponse, error) {
	return i.Service.GetJob(req)
}
