// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: overload.proto

package overload

import (
	"context"

	desc "github.com/x-yield/over-api/pkg/overload-service"
)

func (i *Implementation) ListArtifacts(ctx context.Context, req *desc.ListArtifactsRequest) (*desc.ListArtifactsResponse, error) {
	return i.Service.ListArtifacts(req)
}
