// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: overload.proto

package overload

import (
	"context"
	"github.com/utrack/clay/v2/transport/httpruntime"
	"github.com/x-yield/over-api/tools"

	desc "github.com/x-yield/over-api/pkg/overload-service"
)

func init() {
	httpruntime.OverrideParametrizedMarshaler("multipart/form-data", tools.MultipartFormMarshalerGetter)
}

// Принимает запрос с multipart телом. в нем должна быть job, имя файла, и собственно файл
func (i *Implementation) UploadArtifact(ctx context.Context, req *desc.UploadArtifactRequest) (*desc.UploadArtifactResponse, error) {
	return i.Service.UploadArtifact(req)
}
