// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: overload.proto

package overload

import (
	"context"
	"github.com/utrack/clay/v2/transport/httpruntime"
	"github.com/x-yield/over-api/tools"

	desc "github.com/x-yield/over-api/pkg/overload-service"
)

func init() {
	httpruntime.OverrideParametrizedMarshaler("multipart/form-data", tools.MultipartFormMarshalerGetter)
}

func (i *Implementation) UploadAmmo(ctx context.Context, req *desc.UploadAmmoRequest) (*desc.UploadAmmoResponse, error) {
	return i.Service.UploadAmmo(req)
}
